name: Docker devcontainer image

on:
  push:
    branches:
      - master
    paths:
      - 'docker-images/devcontainer/Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-20.04
    env:
      IMAGE_TAG: '1.0.0'
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build --no-cache \
          --progress=plain \
          --tag $DOCKER_USERNAME/pydeps-devcontainer:$IMAGE_TAG \
          --file docker-images/devcontainer/Dockerfile .

      - name: Push image to Docker Hub
        run: |
          docker push $DOCKER_USERNAME/pydeps-devcontainer:$IMAGE_TAG

# Built with ‚ù§ by [Pipeline Foundation](https://pipeline.foundation)
